### ISSUE TITLE
Show a job history feed, allowing new entries to be created

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#13]

**Comment by bwobbones** [comment]
These notes can be edited, but not deleted.

**Comment by bwobbones** [comment]
Also - use the new job title field

**Comment by patevn** [comment]
things Grady wanted

-if someone edits a message it stays at the same place in the order but it gets flagged as red so we know it had been edited

-put a time since posted so it will come up like "2 hours ago"

-make it more like sms, So you type the message as the bottom and click add form there and the newest message is at the bottom
- if comment is edited the date stamp will not get updated. it stays as when the original comment is posted

**Comment by patevn** [comment]
reverse array

**Comment by patevn** [comment]
support for multiple lines

**Comment by bwobbones** [comment]
Don't show the "for SB12313" in the title when there is no current job

**Comment by patevn** [comment]
done
